# Project Diary

**I have decided that as I already have the fixed broadband data stored in a MongoDb collection that it would be a good idea to clean and import the census data into the same MongoDb instance as its own collection.  I have looked at the census spreadsheets and have decided to form a question using the employment data and combine this with the fixed broadband to form a second question.**

In [1]:
#import libraries
import pandas as pd
import numpy as np
import pymongo
import re
import chardet
import glob 
import folium

In [2]:
#runs the TMA2 Q1 notebook containing the fixed broadband mongodb collection
%run K4782084_q1_TMA02-Copy1.ipynb

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
2023J_TMA02_data/Ofcom_fixed/201909_fixed_laua_coverage_r01.csv
laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),% of premises unable to receive 2Mbit/s,% of premises unable to receive 5Mbit/s,% of premises unable to receive 10Mbit/s,% of premises unable to receive 30Mbit/s,% of premises below the USO,% of premises with NGA,% of premises able to receive decent broadband from FWA,% of premises able to receive SFBB from FWA,Number of premises with SFBB availability,Number of premises with UFBB availability,Number of premises with Full Fibre availability,Number of premises unable to receive 2Mbit/s,Number of pre


2023J_TMA02_data/Ofcom_fixed/202209_fixed_laua_coverage_r02.csv
laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,% of premises unable to receive 5Mbit/s,% of premises unable to receive 10Mbit/s,% of premises unable to receive 30Mbit/s,% of premises below the USO,% of premises with NGA,% of premises able to receive decent broadband from FWA,Number of premises with SFBB availability,Number of premises with UFBB (100Mbit/s) availability,Number of premises with UFBB availability,Number of premises with Full Fibre availability,Number of premises with Gigabit availability,Number of premises unable to receive 2Mbit/s,Number of premises unable to receive 5Mbit/s,Number of premises unable to receive 10Mbit/s,Number of premises unable to receive 30Mbit/s,Number of premises below the

,laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),% of premises unable to receive 2Mbit/s,% of premises unable to receive 5Mbit/s,% of premises unable to receive 10Mbit/s,...,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
0,S12000033,ABERDEEN CITY,125441,125311,73.3,20.1,13.1,0.0,0.2,0.7,...,49,170,665,7275,73.3,20.1,0.0,0.1,0.5,5.8
1,S12000034,ABERDEENSHIRE,125085,124305,78.5,2.8,2.7,2.5,5.9,9.9,...,3163,4176,4993,10321,78.5,2.8,2.5,3.3,4.0,8.3
2,E07000223,ADUR,29770,29760,16.3,82.4,0.6,0.0,0.1,0.1,...,0,16,28,333,16.3,82.4,0.0,0.1,0.1,1.1
3,E07000026,ALLERDALE,51385,51284,89.8,1.7,1.7,1.2,2.6,3.6,...,619,704,550,2408,89.8,1.7,1.2,1.4,1.1,4.7
4,E07000032,AMBER VALLEY,60674,60596,67.4,25.3,22.1,0.1,0.9,2.1,...,89,460,705,3110,67.4,25.3,0.1,0.8,1.2,5.1


laua                                                            0
laua_name                                                       0
All Premises                                                    0
All Matched Premises                                            0
SFBB availability (% premises)                                  0
UFBB availability (% premises)                                  0
Full Fibre availability (% premises)                            0
% of premises unable to receive 2Mbit/s                         0
% of premises unable to receive 5Mbit/s                         0
% of premises unable to receive 10Mbit/s                        0
% of premises unable to receive 30Mbit/s                        0
% of premises below the USO                                     0
% of premises with NGA                                          0
% of premises able to receive decent broadband from FWA         0
% of premises able to receive SFBB from FWA                     0
Number of 

,laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,...,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
0,S12000033,ABERDEEN CITY,126176,125948,94.6,49.0,41.6,34.9,34.9,0.0,...,55,153,673,5709,53.0,41.6,0.0,0.1,0.5,4.5
1,S12000034,ABERDEENSHIRE,126065,125176,82.9,7.2,7.0,6.9,6.9,2.6,...,3234,3865,4417,9188,75.8,7.0,2.6,3.1,3.5,7.3
2,E07000223,ADUR,29779,29755,98.8,85.8,85.6,0.6,0.6,0.0,...,0,10,24,294,13.2,85.6,0.0,0.0,0.1,1.0
3,E07000026,ALLERDALE,51647,51483,92.3,2.8,2.8,2.8,2.8,1.2,...,627,546,532,2085,89.5,2.8,1.2,1.1,1.0,4.0
4,E07000032,AMBER VALLEY,61134,60972,94.7,30.2,26.7,23.6,23.6,0.1,...,63,217,293,2524,68.0,26.7,0.1,0.4,0.5,4.1


laua                                                            0
laua_name                                                       0
All Premises                                                    0
All Matched Premises                                            0
SFBB availability (% premises)                                  0
UFBB (100Mbit/s) availability (% premises)                      0
UFBB availability (% premises)                                  0
Full Fibre availability (% premises)                            0
Gigabit availability (% premises)                               0
% of premises unable to receive 2Mbit/s                         0
% of premises unable to receive 5Mbit/s                         0
% of premises unable to receive 10Mbit/s                        0
% of premises unable to receive 30Mbit/s                        0
% of premises below the USO                                     0
% of premises with NGA                                          0
% of premi

,laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,...,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
0,S12000033,ABERDEEN CITY,129315,129197,97.2,84.8,83.9,83.0,83.0,0.0,...,58,151,222,3130,13.2,83.9,0.0,0.1,0.2,2.4
1,S12000034,ABERDEENSHIRE,128408,128070,85.9,25.5,25.5,25.4,25.4,1.7,...,2214,3193,4296,8071,60.4,25.5,1.7,2.5,3.3,6.3
2,E07000223,ADUR,29985,29953,99.1,92.8,92.8,65.4,92.8,0.0,...,0,9,31,186,6.3,92.8,0.0,0.0,0.1,0.6
3,E07000026,ALLERDALE,52482,52364,93.1,6.0,6.0,6.0,6.0,1.2,...,617,440,422,2000,87.2,6.0,1.2,0.8,0.8,3.8
4,E07000032,AMBER VALLEY,62512,62430,97.2,62.4,60.6,59.0,59.1,0.1,...,42,115,88,1415,36.6,60.6,0.1,0.2,0.1,2.3


laua                                                            0
laua_name                                                       0
All Premises                                                    0
All Matched Premises                                            0
SFBB availability (% premises)                                  0
UFBB (100Mbit/s) availability (% premises)                      0
UFBB availability (% premises)                                  0
Full Fibre availability (% premises)                            0
Gigabit availability (% premises)                               0
% of premises unable to receive 2Mbit/s                         0
% of premises unable to receive 5Mbit/s                         0
% of premises unable to receive 10Mbit/s                        0
% of premises unable to receive 30Mbit/s                        0
% of premises below the USO                                     0
% of premises with NGA                                          0
% of premi

,laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,...,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
0,S12000033,ABERDEEN CITY,127714,126771,94.7,66.6,62.1,58.4,58.4,0.1,...,67,144,417,5205,32.5,62.1,0.1,0.1,0.3,4.1
1,S12000034,ABERDEENSHIRE,126481,125378,82.8,13.8,13.7,13.7,13.7,2.5,...,3202,3984,4445,8986,69.1,13.7,2.5,3.1,3.5,7.1
2,E07000223,ADUR,29884,29793,98.6,85.9,85.6,1.8,1.8,0.0,...,4,9,23,281,13.0,85.6,0.0,0.0,0.1,0.9
3,E07000026,ALLERDALE,51933,51622,92.3,3.4,3.4,3.4,3.4,1.1,...,595,503,514,2088,88.9,3.4,1.1,1.0,1.0,4.0
4,E07000032,AMBER VALLEY,61555,61161,95.1,31.4,27.9,25.2,25.2,0.1,...,61,129,189,2266,67.2,27.9,0.1,0.2,0.3,3.7


laua                                                            0
laua_name                                                       0
All Premises                                                    0
All Matched Premises                                            0
SFBB availability (% premises)                                  0
UFBB (100Mbit/s) availability (% premises)                      0
UFBB availability (% premises)                                  0
Full Fibre availability (% premises)                            0
Gigabit availability (% premises)                               0
% of premises unable to receive 2Mbit/s                         0
% of premises unable to receive 5Mbit/s                         0
% of premises unable to receive 10Mbit/s                        0
% of premises unable to receive 30Mbit/s                        0
% of premises below the USO                                     0
% of premises with NGA                                          0
% of premi

,laua,laua_name,All Premises,All Matched Premises,SFBB availability (% premises),UFBB (100Mbit/s) availability (% premises),UFBB availability (% premises),Full Fibre availability (% premises),Gigabit availability (% premises),% of premises unable to receive 2Mbit/s,...,Number of premises with 0<2Mbit/s download speed,Number of premises with 2<5Mbit/s download speed,Number of premises with 5<10Mbit/s download speed,Number of premises with 10<30Mbit/s download speed,% of premises with 30<300Mbit/s download speed,% of premises with >=300Mbit/s download speed,% of premises with 0<2Mbit/s download speed,% of premises with 2<5Mbit/s download speed,% of premises with 5<10Mbit/s download speed,% of premises with 10<30Mbit/s download speed
0,S12000033,ABERDEEN CITY,128708,128294,95.8,79.1,77.1,74.4,74.4,0.0,...,59,119,370,4411,18.8,77.1,0.0,0.1,0.3,3.4
1,S12000034,ABERDEENSHIRE,127941,127265,84.2,20.6,20.5,20.5,20.5,1.8,...,2330,3450,4660,9083,63.7,20.5,1.8,2.7,3.6,7.1
2,E07000223,ADUR,29971,29920,99.1,91.0,91.0,54.5,90.1,0.0,...,2,6,39,186,8.1,91.0,0.0,0.0,0.1,0.6
3,E07000026,ALLERDALE,52309,52133,92.7,5.4,5.4,5.4,5.4,1.2,...,630,456,455,2093,87.3,5.4,1.2,0.9,0.9,4.0
4,E07000032,AMBER VALLEY,62170,61902,96.1,49.4,46.2,43.6,43.7,0.1,...,58,103,126,1855,49.9,46.2,0.1,0.2,0.2,3.0


laua                                                            0
laua_name                                                       0
All Premises                                                    0
All Matched Premises                                            0
SFBB availability (% premises)                                  0
UFBB (100Mbit/s) availability (% premises)                      0
UFBB availability (% premises)                                  0
Full Fibre availability (% premises)                            0
Gigabit availability (% premises)                               0
% of premises unable to receive 2Mbit/s                         0
% of premises unable to receive 5Mbit/s                         0
% of premises unable to receive 10Mbit/s                        0
% of premises unable to receive 30Mbit/s                        0
% of premises below the USO                                     0
% of premises with NGA                                          0
% of premi

In [3]:
file_list = glob.glob('2023J_TMA02_data/Census/*.xlsx')
file_list

['2023J_TMA02_data/Census/nomis_2023_08_06_172146.xlsx',
 '2023J_TMA02_data/Census/nomis_2023_08_06_174635.xlsx',
 '2023J_TMA02_data/Census/nomis_2023_08_06_232642.xlsx']

The xlsx suffix shows these are excel files.  I 've already opened the files in excel and briefly investigated the results

In [4]:
for f in file_list:
    print(f,':',f.rsplit('/',1)[1][:-4])

2023J_TMA02_data/Census/nomis_2023_08_06_172146.xlsx : nomis_2023_08_06_172146.
2023J_TMA02_data/Census/nomis_2023_08_06_174635.xlsx : nomis_2023_08_06_174635.
2023J_TMA02_data/Census/nomis_2023_08_06_232642.xlsx : nomis_2023_08_06_232642.


In [5]:
dfs = {}
for f in file_list:
    year = f.rsplit('/',1)
    year =  'df_' + year[1]
    df = pd.read_excel(f, sheet_name=None)

    dfs[year] = df
    
    
    

Below shows all three excel files in the dfs collection

In [6]:
print(dfs.keys())

dict_keys(['df_nomis_2023_08_06_172146.xlsx', 'df_nomis_2023_08_06_174635.xlsx', 'df_nomis_2023_08_06_232642.xlsx'])


Below the sheets of each file are shown 

In [7]:
for f in dfs.keys():
    print(dfs[f].keys())
    print()

dict_keys(['Aged 15 years and under', 'Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years', 'Aged 50 to 64 years', 'Aged 65 years and over'])

dict_keys(['Age 16 to 19', 'Age 20 to 21', 'Age 22 to 24', 'Age 25 to 29', 'Age 30 to 34', 'Age 35 to 39', 'Age 40 to 44', 'Age 45 to 49', 'Age 50 to 54', 'Age 55 to 59', 'Age 60 to 64', 'Age 65 and over'])

dict_keys(['Age 16 to 19', 'Age 20 to 24', 'Age 25 and over'])



In [8]:
print(dfs['df_nomis_2023_08_06_174635.xlsx'].keys())

dict_keys(['Age 16 to 19', 'Age 20 to 21', 'Age 22 to 24', 'Age 25 to 29', 'Age 30 to 34', 'Age 35 to 39', 'Age 40 to 44', 'Age 45 to 49', 'Age 50 to 54', 'Age 55 to 59', 'Age 60 to 64', 'Age 65 and over'])


In [9]:
dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21']

,DC6107EW - Economic Activity by sex by age,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,ONS Crown Copyright Reserved [from Nomis on 6 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,population,All usual residents aged 16 and over,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,units,Persons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,date,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
354,Torfaen,W06000020,563,854,11,39,380,1,167,96,64,67
355,Monmouthshire,W06000021,385,681,16,46,222,0,146,55,31,55
356,Newport,W06000022,1125,1097,25,37,674,3,843,161,81,139
357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [10]:
dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21'][:12]

,DC6107EW - Economic Activity by sex by age,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,ONS Crown Copyright Reserved [from Nomis on 6 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,population,All usual residents aged 16 and over,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,units,Persons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,date,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,sex,All persons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,age,Age 20 to 21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,local authority: district / unitary (prior to ...,NaN,Economically active: In employment: Employee: ...,Economically active: In employment: Employee: ...,Economically active: In employment: Self-emplo...,Economically active: In employment: Self-emplo...,Economically active: Unemployed (including ful...,Economically inactive: Retired,Economically inactive: Student (including full...,Economically inactive: Looking after home or f...,Economically inactive: Long-term sick or disabled,Economically inactive: Other
9,Darlington,E06000005,624,857,13,22,369,1,186,112,47,68


In [11]:
dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21'].tail()

,DC6107EW - Economic Activity by sex by age,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
354,Torfaen,W06000020,563,854,11,39,380,1,167,96,64,67
355,Monmouthshire,W06000021,385,681,16,46,222,0,146,55,31,55
356,Newport,W06000022,1125,1097,25,37,674,3,843,161,81,139
357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [12]:
#convert the spreadsheets into dataframes and store in a dictionary
test_dfs = {}
for f in file_list:
    year = f.rsplit('/',1)
    year =  'df_' + year[1]
    df = pd.read_excel(f, sheet_name=None, skiprows=8, skipfooter=2)

    test_dfs[year] = df
    
#check the head and tail of each sheet    
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    print(i)
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].head())
    print(i + ' tail')
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].tail())

Aged 15 years and under
                         Unnamed: 0 Unnamed: 1  \
0  2022 local authorities: district        NaN   
1                        Hartlepool  E06000001   
2                     Middlesbrough  E06000002   
3              Redcar and Cleveland  E06000003   
4                  Stockton-on-Tees  E06000004   

                                          Unnamed: 2  \
0  Economically active (excluding full-time stude...   
1                                                  0   
2                                                  0   
3                                                  0   
4                                                  0   

                                          Unnamed: 3  \
0  Economically active (excluding full-time stude...   
1                                                  0   
2                                                  0   
3                                                  0   
4                                                  0   

 

Below I grab the correct column names and rename the columns, the cell after next shows this has been successful

In [13]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    new_cols = test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].loc[0].tolist()
    old_cols = test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].columns
    new_cols[1] = 'laua_code'
    for j in range(len(old_cols)):
        test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].rename(columns= {old_cols[j]: new_cols[j]}, inplace =True)
        

In [14]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    print(i)
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].head())
    print(i + ' tail')
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].tail())

Aged 15 years and under
   2022 local authorities: district  laua_code  \
0  2022 local authorities: district        NaN   
1                        Hartlepool  E06000001   
2                     Middlesbrough  E06000002   
3              Redcar and Cleveland  E06000003   
4                  Stockton-on-Tees  E06000004   

  Economically active (excluding full-time students): In employment  \
0  Economically active (excluding full-time stude...                  
1                                                  0                  
2                                                  0                  
3                                                  0                  
4                                                  0                  

  Economically active (excluding full-time students): Unemployed  \
0  Economically active (excluding full-time stude...               
1                                                  0               
2                                           

The output above shows that the columns have been successfully renamed.  I will now drop the first row from each and reset the indexes and I should have all the correct rows and column names for each excel sheet in the 2021 employment data

In [15]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].drop([0], inplace=True)
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].reset_index(inplace=True)

In [16]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    print(i)
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].head())
    

Aged 15 years and under
   index 2022 local authorities: district  laua_code  \
0      1                       Hartlepool  E06000001   
1      2                    Middlesbrough  E06000002   
2      3             Redcar and Cleveland  E06000003   
3      4                 Stockton-on-Tees  E06000004   
4      5                       Darlington  E06000005   

  Economically active (excluding full-time students): In employment  \
0                                                  0                  
1                                                  0                  
2                                                  0                  
3                                                  0                  
4                                                  0                  

  Economically active (excluding full-time students): Unemployed  \
0                                                  0               
1                                                  0               
2       

The above shows a new index column has been created we'll drop that, check again and move on

In [17]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].drop(['index'], axis=1, inplace=True)
    #check all dataframes are the same length
    print(len(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i]))
    
test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 50 to 64 years'].head()

331
331
331
331
331
331


,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student
0,Hartlepool,E06000001,12347,686,20,1,6903,48
1,Middlesbrough,E06000002,16249,1023,33,5,9452,63
2,Redcar and Cleveland,E06000003,18712,955,45,6,10437,75
3,Stockton-on-Tees,E06000004,26805,1235,51,4,12480,100
4,Darlington,E06000005,15448,668,32,7,6410,64


Right now I'm getting somewhere i'll add the age group as a column as this will need to be a key value pair in the MongoDb collection.  I will also calculate some totals and add them as new columns like total residents, total unemployed, total in employment

In [18]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i]['Age Group'] = i
test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 15 years and under'].head()
    

,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student,Age Group
0,Hartlepool,E06000001,0,0,0,0,0,0,Aged 15 years and under
1,Middlesbrough,E06000002,0,0,0,0,0,0,Aged 15 years and under
2,Redcar and Cleveland,E06000003,0,0,0,0,0,0,Aged 15 years and under
3,Stockton-on-Tees,E06000004,0,0,0,0,0,0,Aged 15 years and under
4,Darlington,E06000005,0,0,0,0,0,0,Aged 15 years and under


In [19]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].dtypes)
    

2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment    object
Economically active (excluding full-time students): Unemployed       object
Economically active and a full-time student: In employment           object
Economically active and a full-time student: Unemployed              object
Economically inactive (excluding full-time students)                 object
Economically inactive and a full-time student                        object
Age Group                                                            object
dtype: object
2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment    object
Economically active (excluding full-time students): Unemployed       objec

**THe cell above shows the data types are all objects, in order to work with the numerical data I shall have to change them to integer data types**

In [20]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    cols = test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].columns
    
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i] = test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].convert_dtypes(convert_string=False)

In [21]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].dtypes)

2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment     Int64
Economically active (excluding full-time students): Unemployed        Int64
Economically active and a full-time student: In employment            Int64
Economically active and a full-time student: Unemployed               Int64
Economically inactive (excluding full-time students)                  Int64
Economically inactive and a full-time student                         Int64
Age Group                                                            object
dtype: object
2022 local authorities: district                                     object
laua_code                                                            object
Economically active (excluding full-time students): In employment     Int64
Economically active (excluding full-time students): Unemployed        Int6

**The cell below adds some columns which collect the data points in the original spreadsheet, this could be useful later as the 2011 and 2021 columns are different both in number and in definition.  By collecting the columns into totals direct comparisons can be made between the data from these years, I will also keep all of the existing columns.** 

In [22]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    cols = test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].columns[2:-1]   
    total = []
    active = []
    inactive = []
    employed = []
    for index, row in test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].iterrows():
        total.append(row[cols].sum())
        active.append(row[cols[:-2]].sum())
        inactive.append(row[cols[4:]].sum())
        employed.append(row[cols[0]] + row[cols[2]]) # the cols[2] here was initially cols[3] but that was incorrect 
                                                    #this is mentioned below
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i]['Total Residents'] = total
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i]['Total Active'] = active
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i]['Total Inactive'] = inactive
    test_dfs['df_nomis_2023_08_06_172146.xlsx'][i]['Total Employed'] = employed  
    

The following two cells check to see if the changes made have been successful

In [23]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    print(test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].head())

  2022 local authorities: district  laua_code  \
0                       Hartlepool  E06000001   
1                    Middlesbrough  E06000002   
2             Redcar and Cleveland  E06000003   
3                 Stockton-on-Tees  E06000004   
4                       Darlington  E06000005   

   Economically active (excluding full-time students): In employment  \
0                                                  0                   
1                                                  0                   
2                                                  0                   
3                                                  0                   
4                                                  0                   

   Economically active (excluding full-time students): Unemployed  \
0                                                  0                
1                                                  0                
2                                                  0             

In [24]:
test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 16 to 24 years']

,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student,Age Group,Total Residents,Total Active,Total Inactive,Total Employed
0,Hartlepool,E06000001,3288,671,709,338,1100,3018,Aged 16 to 24 years,9124,5006,4118,3997
1,Middlesbrough,E06000002,4811,1079,1656,995,1916,6486,Aged 16 to 24 years,16943,8541,8402,6467
2,Redcar and Cleveland,E06000003,4741,916,932,422,1385,3795,Aged 16 to 24 years,12191,7011,5180,5673
3,Stockton-on-Tees,E06000004,6766,1188,1598,684,1945,5724,Aged 16 to 24 years,17905,10236,7669,8364
4,Darlington,E06000005,4284,697,881,334,984,2788,Aged 16 to 24 years,9968,6196,3772,5165
...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,Torfaen,W06000020,3645,608,622,270,936,2398,Aged 16 to 24 years,8479,5145,3334,4267
327,Monmouthshire,W06000021,3169,417,601,194,629,2471,Aged 16 to 24 years,7481,4381,3100,3770
328,Newport,W06000022,6003,1082,1358,617,1561,4902,Aged 16 to 24 years,15523,9060,6463,7361
329,Powys,W06000023,5059,502,785,191,876,3335,Aged 16 to 24 years,10748,6537,4211,5844


Now i'll check that the calculations have been done correctly by testing the top rows figures

In [25]:
3288+671+709+338 +1100 + 3018 #expecting 9124 as in df

9124

In [26]:
3288+671+709+338 #expecting 5006 as in the df

5006

In [27]:
1100 + 3018 # expecting 4118 as in the df 

4118

In [28]:
3288 + 709 #expecting 3626 as in df

3997

Ah right now we have an issue the above output is 3997 which means the figure in the df has been calculated wrongly, I'll change the code used to calculate this figure and check the df again to see if the result is 3997 in the total employed column

In [29]:
test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 16 to 24 years'].head()

,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student,Age Group,Total Residents,Total Active,Total Inactive,Total Employed
0,Hartlepool,E06000001,3288,671,709,338,1100,3018,Aged 16 to 24 years,9124,5006,4118,3997
1,Middlesbrough,E06000002,4811,1079,1656,995,1916,6486,Aged 16 to 24 years,16943,8541,8402,6467
2,Redcar and Cleveland,E06000003,4741,916,932,422,1385,3795,Aged 16 to 24 years,12191,7011,5180,5673
3,Stockton-on-Tees,E06000004,6766,1188,1598,684,1945,5724,Aged 16 to 24 years,17905,10236,7669,8364
4,Darlington,E06000005,4284,697,881,334,984,2788,Aged 16 to 24 years,9968,6196,3772,5165


Im happy with the above I'll now try to create a dataframe containing data from all of the files

In [30]:
combined_2021_df = test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 15 years and under']

In [31]:
combined_2021_df 

,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student,Age Group,Total Residents,Total Active,Total Inactive,Total Employed
0,Hartlepool,E06000001,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
1,Middlesbrough,E06000002,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
2,Redcar and Cleveland,E06000003,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
3,Stockton-on-Tees,E06000004,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
4,Darlington,E06000005,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,Torfaen,W06000020,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
327,Monmouthshire,W06000021,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
328,Newport,W06000022,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0
329,Powys,W06000023,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0


In [32]:
for i in test_dfs['df_nomis_2023_08_06_172146.xlsx']:
    if i != 'Aged 15 years and under':
        combined_2021_df = pd.concat([test_dfs['df_nomis_2023_08_06_172146.xlsx'][i], combined_2021_df])


Check the above has the right amount of rows (6 dfs of 331 rows)


In [33]:
1986/6

331.0

In [34]:
combined_2021_df['2022 local authorities: district'] = combined_2021_df['2022 local authorities: district'].str.upper()

Above I've converted the district names to upper case as this is how they are in the fixed broadband data.  I'll now add the year column which will be required as a key-value in the MongoDb instance

In [35]:
combined_2021_df['Year'] = 2021

In [36]:
combined_2021_df

,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student,Age Group,Total Residents,Total Active,Total Inactive,Total Employed,Year
0,HARTLEPOOL,E06000001,1339,51,1,0,16820,22,Aged 65 years and over,18233,1391,16842,1340,2021
1,MIDDLESBROUGH,E06000002,1933,87,2,0,22131,25,Aged 65 years and over,24178,2022,22156,1935,2021
2,REDCAR AND CLEVELAND,E06000003,2169,75,4,0,29472,29,Aged 65 years and over,31749,2248,29501,2173,2021
3,STOCKTON-ON-TEES,E06000004,3174,103,2,1,33868,36,Aged 65 years and over,37184,3280,33904,3176,2021
4,DARLINGTON,E06000005,1873,54,1,0,20090,22,Aged 65 years and over,22040,1928,20112,1874,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,TORFAEN,W06000020,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0,2021
327,MONMOUTHSHIRE,W06000021,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0,2021
328,NEWPORT,W06000022,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0,2021
329,POWYS,W06000023,0,0,0,0,0,0,Aged 15 years and under,0,0,0,0,2021


In [37]:
#check for null values
combined_2021_df.isna().sum()

2022 local authorities: district                                     0
laua_code                                                            0
Economically active (excluding full-time students): In employment    0
Economically active (excluding full-time students): Unemployed       0
Economically active and a full-time student: In employment           0
Economically active and a full-time student: Unemployed              0
Economically inactive (excluding full-time students)                 0
Economically inactive and a full-time student                        0
Age Group                                                            0
Total Residents                                                      0
Total Active                                                         0
Total Inactive                                                       0
Total Employed                                                       0
Year                                                                 0
dtype:

I'm happy that the above data frame contains a row for each age group and local authority for the year 2021,  I will now attempt to do the same with the 2011 data, making sure to amalgamate the local authorities to match those in the 2021 data

In [38]:
a = test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 16 to 24 years']['2022 local authorities: district'].tolist()
print(a)

['Hartlepool', 'Middlesbrough', 'Redcar and Cleveland', 'Stockton-on-Tees', 'Darlington', 'County Durham', 'Northumberland', 'Newcastle upon Tyne', 'North Tyneside', 'South Tyneside', 'Sunderland', 'Gateshead', 'Halton', 'Warrington', 'Blackburn with Darwen', 'Blackpool', 'Cheshire East', 'Cheshire West and Chester', 'Allerdale', 'Barrow-in-Furness', 'Carlisle', 'Copeland', 'Eden', 'South Lakeland', 'Burnley', 'Chorley', 'Fylde', 'Hyndburn', 'Lancaster', 'Pendle', 'Preston', 'Ribble Valley', 'Rossendale', 'South Ribble', 'West Lancashire', 'Wyre', 'Bolton', 'Bury', 'Manchester', 'Oldham', 'Rochdale', 'Salford', 'Stockport', 'Tameside', 'Trafford', 'Wigan', 'Knowsley', 'Liverpool', 'St. Helens', 'Sefton', 'Wirral', 'Kingston upon Hull, City of', 'East Riding of Yorkshire', 'North East Lincolnshire', 'North Lincolnshire', 'York', 'Craven', 'Hambleton', 'Harrogate', 'Richmondshire', 'Ryedale', 'Scarborough', 'Selby', 'Barnsley', 'Doncaster', 'Rotherham', 'Sheffield', 'Bradford', 'Calderda

# Cleaning the 2011 data

The first few steps will be the same as with the 2021 data, i'll rename the columns and drop the meta rows

In [39]:
#check the head and tail of each sheet as before
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    print(i)
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].head())
    print(i + ' tail')
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].tail())

Age 16 to 19
                                          Unnamed: 0 Unnamed: 1  \
0  local authority: district / unitary (prior to ...        NaN   
1                                         Darlington  E06000005   
2                                      County Durham  E06000047   
3                                         Hartlepool  E06000001   
4                                      Middlesbrough  E06000002   

                                          Unnamed: 2  \
0  Economically active: In employment: Employee: ...   
1                                               1246   
2                                               4930   
3                                                884   
4                                               1542   

                                          Unnamed: 3  \
0  Economically active: In employment: Employee: ...   
1                                                619   
2                                               3344   
3                      

In [40]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    new_cols = test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].loc[0].tolist()
    old_cols = test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].columns
    new_cols[1] = 'laua_code'
    for j in range(len(old_cols)):
        test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].rename(columns= {old_cols[j]: new_cols[j]}, inplace =True)
        

In [41]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    print(i)
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].head())
    print(i + ' tail')
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].tail())

Age 16 to 19
  local authority: district / unitary (prior to April 2015)  laua_code  \
0  local authority: district / unitary (prior to ...               NaN   
1                                         Darlington         E06000005   
2                                      County Durham         E06000047   
3                                         Hartlepool         E06000001   
4                                      Middlesbrough         E06000002   

  Economically active: In employment: Employee: Part-time (including full-time students)  \
0  Economically active: In employment: Employee: ...                                       
1                                               1246                                       
2                                               4930                                       
3                                                884                                       
4                                               1542                              

    local authority: district / unitary (prior to April 2015)  laua_code  \
344                                         Caerphilly         W06000018   
345                                      Blaenau Gwent         W06000019   
346                                            Torfaen         W06000020   
347                                      Monmouthshire         W06000021   
348                                            Newport         W06000022   

    Economically active: In employment: Employee: Part-time (including full-time students)  \
344                                                713                                       
345                                                283                                       
346                                                424                                       
347                                                700                                       
348                                                763                   

In [42]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].drop([0], inplace=True)
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].reset_index(inplace=True)

In [43]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    print(i)
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].head())
    

Age 16 to 19
   index local authority: district / unitary (prior to April 2015)  laua_code  \
0      1                                         Darlington         E06000005   
1      2                                      County Durham         E06000047   
2      3                                         Hartlepool         E06000001   
3      4                                      Middlesbrough         E06000002   
4      5                                     Northumberland         E06000057   

  Economically active: In employment: Employee: Part-time (including full-time students)  \
0                                               1246                                       
1                                               4930                                       
2                                                884                                       
3                                               1542                                       
4                                       

In [44]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].drop(['index'], axis=1, inplace=True)
    #check all dataframes are the same length
    print(len(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i]))

348
348
348
348
348
348
348
348
348
348
348
348


In [45]:
test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21']

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other
0,Darlington,E06000005,624,857,13,22,369,1,186,112,47,68
1,County Durham,E06000047,3177,3903,100,169,1808,9,5552,548,281,594
2,Hartlepool,E06000001,536,667,9,24,541,1,223,144,42,83
3,Middlesbrough,E06000002,1223,907,38,42,927,4,1280,206,82,185
4,Northumberland,E06000057,1494,2479,55,126,914,4,587,234,137,209
...,...,...,...,...,...,...,...,...,...,...,...,...
343,Caerphilly,W06000018,873,1552,25,82,750,2,388,219,111,147
344,Blaenau Gwent,W06000019,396,582,7,35,386,5,165,118,46,83
345,Torfaen,W06000020,563,854,11,39,380,1,167,96,64,67
346,Monmouthshire,W06000021,385,681,16,46,222,0,146,55,31,55


In [46]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].dtypes)

local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)         object
Economically active: In employment: Employee: Full-time (including full-time students)         object
Economically active: In employment: Self-employed: Part-time (including full-time students)    object
Economically active: In employment: Self-employed: Full-time (including full-time students)    object
Economically active: Unemployed (including full-time students)                                 object
Economically inactive: Retired                                                                 object
Economically inactive: Student (including full-time students)                                  object
Economically inactive: Looking after home or family                               

Again the datatypes of the integer columns have to be changed

In [47]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    cols = test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].columns
    #test_dfs['df_nomis_2023_08_06_172146.xlsx'][i][new_cols[2:-1]].astype(int)test_dfs['df_nomis_2023_08_06_172146.xlsx'][i].convert_dtypes(convert)
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i] = test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].convert_dtypes(convert_string=False)

In [48]:
#check again
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].dtypes)

local authority: district / unitary (prior to April 2015)                                      object
laua_code                                                                                      object
Economically active: In employment: Employee: Part-time (including full-time students)          Int64
Economically active: In employment: Employee: Full-time (including full-time students)          Int64
Economically active: In employment: Self-employed: Part-time (including full-time students)     Int64
Economically active: In employment: Self-employed: Full-time (including full-time students)     Int64
Economically active: Unemployed (including full-time students)                                  Int64
Economically inactive: Retired                                                                  Int64
Economically inactive: Student (including full-time students)                                   Int64
Economically inactive: Looking after home or family                               

In [49]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].isna().sum())
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].describe())

local authority: district / unitary (prior to April 2015)                                      0
laua_code                                                                                      0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-te

       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0                                        
mean                                         1125.798851                                        
std                                          1095.174011                                        
min                                                  4.0                                        
25%                                                486.0                                        
50%                                                711.0                                        
75%                                               1403.5                                        
max                                               9603.0                                        

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                        

       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0                                        
mean                                         1618.206897                                        
std                                          1276.261269                                        
min                                                 27.0                                        
25%                                                891.0                                        
50%                                               1133.5                                        
75%                                              2032.75                                        
max                                              12191.0                                        

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                        

       Economically active: In employment: Employee: Part-time (including full-time students)  \
count                                              348.0                                        
mean                                         1717.905172                                        
std                                          1059.161214                                        
min                                                 23.0                                        
25%                                               1087.0                                        
50%                                               1436.5                                        
75%                                               1954.0                                        
max                                               8674.0                                        

       Economically active: In employment: Employee: Full-time (including full-time students)  \
count                        

**This is where the cleaning will be slightly different, there are more categories of employment activity to take into account, however I want to get the same four columns added; total residents, total active, total inactive and total employed.  I also have to combine age groups as there are more age bands in the 2011 data so I will leave adding the age group to the dataframe until this is done.**

In [50]:
for i in test_dfs['df_nomis_2023_08_06_174635.xlsx']:
    cols = test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].columns[2:]   
    total = []
    active = []
    inactive = []
    employed = []
    for index, row in test_dfs['df_nomis_2023_08_06_174635.xlsx'][i].iterrows():
        total.append(row[cols].sum())
        active.append(row[cols[:5]].sum())
        inactive.append(row[cols[5:]].sum())
        employed.append(row[cols[:4]].sum()) # the cols[2] here was initially cols[3] but that was incorrect 
    
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i]['Total Residents'] = total
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i]['Total Active'] = active
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i]['Total Inactive'] = inactive
    test_dfs['df_nomis_2023_08_06_174635.xlsx'][i]['Total Employed'] = employed  
    

In [51]:
#check new columns in place
test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21']

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Darlington,E06000005,624,857,13,22,369,1,186,112,47,68,2299,1885,414,1516
1,County Durham,E06000047,3177,3903,100,169,1808,9,5552,548,281,594,16141,9157,6984,7349
2,Hartlepool,E06000001,536,667,9,24,541,1,223,144,42,83,2270,1777,493,1236
3,Middlesbrough,E06000002,1223,907,38,42,927,4,1280,206,82,185,4894,3137,1757,2210
4,Northumberland,E06000057,1494,2479,55,126,914,4,587,234,137,209,6239,5068,1171,4154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,Caerphilly,W06000018,873,1552,25,82,750,2,388,219,111,147,4149,3282,867,2532
344,Blaenau Gwent,W06000019,396,582,7,35,386,5,165,118,46,83,1823,1406,417,1020
345,Torfaen,W06000020,563,854,11,39,380,1,167,96,64,67,2242,1847,395,1467
346,Monmouthshire,W06000021,385,681,16,46,222,0,146,55,31,55,1637,1350,287,1128


Now I'll check all the calculations are correct by adding up the relevant figures in one row as before

In [52]:
print(624+857+13+22+369+1+186+112+47+68) #should equal 2299
print(624+857+13+22+369) #should equal 1885
print(1+186+112+47+68) #should equal 414
print(624+857+13+22) #should equal 1516

2299
1885
414
1516


Okay I'm happy with the results above.  I will now combine the age groups to match the 2021 data

In [53]:
test_dfs['df_nomis_2023_08_06_174635.xlsx'].keys()

dict_keys(['Age 16 to 19', 'Age 20 to 21', 'Age 22 to 24', 'Age 25 to 29', 'Age 30 to 34', 'Age 35 to 39', 'Age 40 to 44', 'Age 45 to 49', 'Age 50 to 54', 'Age 55 to 59', 'Age 60 to 64', 'Age 65 and over'])

In [54]:
test_dfs['df_nomis_2023_08_06_172146.xlsx'].keys()

dict_keys(['Aged 15 years and under', 'Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years', 'Aged 50 to 64 years', 'Aged 65 years and over'])

Right I will attempt to combine the three 16 to 24 age bands and store it in a new dictionary 

In [55]:
test_dfs_2011_agecombined = {}

test_dfs_2011_agecombined['Aged 16 to 24 years'] = pd.concat([
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 16 to 19'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 22 to 24']
    ]
)
test_dfs_2011_agecombined.keys() #check its been added

dict_keys(['Aged 16 to 24 years'])

In [56]:
#checked the number of rows, should be 1044 (348 * 3)
test_dfs_2011_agecombined['Aged 16 to 24 years']

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Darlington,E06000005,1246,619,27,16,827,1,2109,77,36,120,5078,2735,2343,1908
1,County Durham,E06000047,4930,3344,85,97,3854,12,13699,397,214,753,27385,12310,15075,8456
2,Hartlepool,E06000001,884,539,12,8,915,1,2382,112,31,137,5021,2358,2663,1443
3,Middlesbrough,E06000002,1542,751,22,23,1460,1,4039,143,52,220,8253,3798,4455,2338
4,Northumberland,E06000057,3388,2130,37,81,2037,17,6363,193,83,294,14623,7673,6950,5636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,Caerphilly,W06000018,1182,3325,48,202,809,5,282,421,213,184,6671,5566,1105,4757
344,Blaenau Gwent,W06000019,498,1311,15,63,406,4,78,193,117,128,2813,2293,520,1887
345,Torfaen,W06000020,653,1653,24,73,364,2,122,234,129,92,3346,2767,579,2403
346,Monmouthshire,W06000021,486,1381,33,111,227,2,136,126,70,102,2674,2238,436,2011


Okay I'm happy that the resultant frame has the correct number of rows, I will now attempt to combine the data for each area, I'll first take note of the total Residents figure for one area so that I can check the figures have been combined correctly

In [57]:
test_dfs_2011_agecombined['Aged 16 to 24 years'].loc[test_dfs_2011_agecombined['Aged 16 to 24 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Darlington,E06000005,1246,619,27,16,827,1,2109,77,36,120,5078,2735,2343,1908
0,Darlington,E06000005,624,857,13,22,369,1,186,112,47,68,2299,1885,414,1516
0,Darlington,E06000005,737,1964,35,81,451,1,106,198,79,120,3772,3268,504,2817


Above shows three entries for Darlington as expected with total resident figures of 5078, 2299 and 3772

In [58]:
cols = test_dfs_2011_agecombined['Aged 16 to 24 years'].columns[2:]
test_dfs_2011_agecombined['Aged 16 to 24 years'] = test_dfs_2011_agecombined['Aged 16 to 24 years'].groupby([
    'local authority: district / unitary (prior to April 2015)', 'laua_code'
])[cols].sum().reset_index()



In [59]:
test_dfs_2011_agecombined['Aged 16 to 24 years']

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Adur,E07000223,1357,1839,66,168,643,4,1265,187,88,122,5739,4073,1666,3430
1,Allerdale,E07000026,2240,3279,48,161,1036,11,1924,209,147,175,9230,6764,2466,5728
2,Amber Valley,E07000032,2454,4287,119,250,1453,5,2754,327,131,283,12063,8563,3500,7110
3,Arun,E07000224,3356,4601,158,350,1500,11,2930,376,194,314,13790,9965,3825,8465
4,Ashfield,E07000170,2522,4450,67,221,1829,9,2638,503,251,377,12867,9089,3778,7260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,Wychavon,E07000238,2466,3677,121,251,961,13,2534,250,108,237,10618,7476,3142,6515
344,Wycombe,E07000007,4128,5784,210,391,1884,11,5665,391,134,434,19032,12397,6635,10513
345,Wyre,E07000128,2659,3326,104,219,1129,9,2664,226,148,182,10666,7437,3229,6308
346,Wyre Forest,E07000239,2215,2937,81,211,1215,5,2137,339,130,264,9534,6659,2875,5444


Okay the above seems to have the correct number of rows however the districts are now in alphabetical order.  I'll look for the darlington row and see if the total residents figure is as expected, i'll also check there are 348 distinct districts

In [60]:
print(len(set(test_dfs_2011_agecombined['Aged 16 to 24 years']['local authority: district / unitary (prior to April 2015)'])))

test_dfs_2011_agecombined['Aged 16 to 24 years'].loc[test_dfs_2011_agecombined['Aged 16 to 24 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

348


,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
79,Darlington,E06000005,2607,3440,75,119,1647,3,2401,387,162,308,11149,7888,3261,6241


In [61]:
5078 +2299 + 3772 #should come to 11149 as shown above

11149

I'll now repeat the above steps with the other age groups

In [62]:
#step 1 create new combined df
test_dfs_2011_agecombined['Aged 25 to 34 years'] = pd.concat([
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 25 to 29'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 30 to 34']
    ]
)

test_dfs_2011_agecombined.keys() #check its been added

dict_keys(['Aged 16 to 24 years', 'Aged 25 to 34 years'])

In [63]:
#step 2 check the correct number of rows are present and note total residents numbers
test_dfs_2011_agecombined['Aged 25 to 34 years'].loc[test_dfs_2011_agecombined['Aged 25 to 34 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Darlington,E06000005,1082,3747,96,226,585,3,112,426,189,141,6607,5736,871,5151
0,Darlington,E06000005,1163,3490,128,331,393,5,66,460,253,140,6429,5505,924,5112


In [64]:
#step 3 groupby authority and laua code
test_dfs_2011_agecombined['Aged 25 to 34 years'] = test_dfs_2011_agecombined['Aged 25 to 34 years'].groupby([
    'local authority: district / unitary (prior to April 2015)', 'laua_code'
])[cols].sum().reset_index()


In [65]:
#step4 check the result
print(len(set(test_dfs_2011_agecombined['Aged 25 to 34 years']['local authority: district / unitary (prior to April 2015)'])))

test_dfs_2011_agecombined['Aged 25 to 34 years'].loc[test_dfs_2011_agecombined['Aged 25 to 34 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

348


,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
79,Darlington,E06000005,2245,7237,224,557,978,8,178,886,442,281,13036,11241,1795,10263


In [66]:
6607+6429 #should be 13036

13036

In [67]:
#step 1 create new combined df
test_dfs_2011_agecombined['Aged 35 to 49 years'] = pd.concat([
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 35 to 39'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 40 to 44'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 45 to 49']
    ]
)

test_dfs_2011_agecombined.keys() #check its been added

dict_keys(['Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years'])

In [68]:
#step 2 check the correct number of rows are present and note total residents numbers
test_dfs_2011_agecombined['Aged 35 to 49 years'].loc[test_dfs_2011_agecombined['Aged 35 to 49 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Darlington,E06000005,1331,3516,155,450,389,10,51,457,362,126,6847,5841,1006,5452
0,Darlington,E06000005,1456,4014,222,609,405,18,39,335,422,121,7641,6706,935,6301
0,Darlington,E06000005,1415,4366,192,664,285,28,29,341,552,122,7994,6922,1072,6637


In [69]:
#step 3 groupby authority and laua code
test_dfs_2011_agecombined['Aged 35 to 49 years'] = test_dfs_2011_agecombined['Aged 35 to 49 years'].groupby([
    'local authority: district / unitary (prior to April 2015)', 'laua_code'
])[cols].sum().reset_index()


In [70]:
#step4 check the result
print(len(set(test_dfs_2011_agecombined['Aged 35 to 49 years']['local authority: district / unitary (prior to April 2015)'])))

test_dfs_2011_agecombined['Aged 35 to 49 years'].loc[test_dfs_2011_agecombined['Aged 35 to 49 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

348


,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
79,Darlington,E06000005,4202,11896,569,1723,1079,56,119,1133,1336,369,22482,19469,3013,18390


In [71]:
6847 + 7641 + 7994 # should equal 22482

22482

In [72]:
#step 1 create new combined df
test_dfs_2011_agecombined['Aged 50 to 64 years'] = pd.concat([
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 50 to 54'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 55 to 59'],
    test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 60 to 64']
    ]
)

test_dfs_2011_agecombined.keys() #check its been added

dict_keys(['Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years', 'Aged 50 to 64 years'])

In [73]:
#step 2 check the correct number of rows are present and note total residents numbers
test_dfs_2011_agecombined['Aged 50 to 64 years'].loc[test_dfs_2011_agecombined['Aged 50 to 64 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Darlington,E06000005,1246,3695,165,646,315,150,19,287,599,136,7258,6067,1191,5752
0,Darlington,E06000005,1086,2645,177,475,276,559,8,284,682,116,6308,4659,1649,4383
0,Darlington,E06000005,908,1395,182,395,106,3092,4,77,406,120,6685,2986,3699,2880


In [74]:
#step 3 groupby authority and laua code
test_dfs_2011_agecombined['Aged 50 to 64 years'] = test_dfs_2011_agecombined['Aged 50 to 64 years'].groupby([
    'local authority: district / unitary (prior to April 2015)', 'laua_code'
])[cols].sum().reset_index()


In [75]:
#step4 check the result
print(len(set(test_dfs_2011_agecombined['Aged 50 to 64 years']['local authority: district / unitary (prior to April 2015)'])))

test_dfs_2011_agecombined['Aged 50 to 64 years'].loc[test_dfs_2011_agecombined['Aged 50 to 64 years']
                                                     ['local authority: district / unitary (prior to April 2015)'] == 'Darlington'
                                                    ]

348


,local authority: district / unitary (prior to April 2015),laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
79,Darlington,E06000005,3240,7735,524,1516,697,3801,31,648,1687,372,20251,13712,6539,13015


In [76]:
7258+6308+6685==20251

True

In [77]:
#finally
test_dfs_2011_agecombined['Aged 65 years and over'] = test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 65 and over']
test_dfs_2011_agecombined.keys() #check its been added

dict_keys(['Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years', 'Aged 50 to 64 years', 'Aged 65 years and over'])

In [78]:
b = test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 20 to 21']['local authority: district / unitary (prior to April 2015)'].tolist()

# combining the districts

The data from 2011 features rows pertaining to local authorities which have been amalgamated by 2022.  The data from the 2021 census defines the local authority as correct at 2022 although the figures are from 2021.  I will check first which areas are unique to the data from both years and see if I can ascertain which districts must be combined.

As there is 348 rows in each 2011 age band and 331 rows in each 2021 age band I will expect there to be 331 in the 2011 data when the changes have been identified and applied

In [79]:
districts_2021 = test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 16 to 24 years']['2022 local authorities: district'].tolist()

In [80]:
districts_2011 = test_dfs_2011_agecombined['Aged 25 to 34 years']['local authority: district / unitary (prior to April 2015)'].tolist()

In [81]:
set(districts_2011).difference(set(districts_2021)) 

{'Aylesbury Vale',
 'Bournemouth',
 'Chiltern',
 'Christchurch',
 'Corby',
 'Daventry',
 'East Dorset',
 'East Northamptonshire',
 'Forest Heath',
 'Kettering',
 'North Dorset',
 'Northampton',
 'Poole',
 'Purbeck',
 'South Bucks',
 'South Northamptonshire',
 'St Edmundsbury',
 'Suffolk Coastal',
 'Taunton Deane',
 'Waveney',
 'Wellingborough',
 'West Dorset',
 'West Somerset',
 'Weymouth and Portland',
 'Wycombe'}

In [82]:
set(districts_2021).difference(set(districts_2011))

{'Bournemouth, Christchurch and Poole',
 'Buckinghamshire',
 'Dorset',
 'East Suffolk',
 'North Northamptonshire',
 'Somerset West and Taunton',
 'West Northamptonshire',
 'West Suffolk'}

The two cells above show the old authorities and their amalgamated counterparts respectively.  Having investigated the 8 council areas in the 2021 data I can see that the 25 areas in the 2011 data shown above do indeed make up these 8 areas.  I will now attempt to make the necessary changes.


In [83]:
#first I'm going to rename the district column to a simpler column header.  Shouldve done this earlier actually.
#im using the same column identifier as the fixed broadband data although I may change this later
for i in test_dfs_2011_agecombined:
    test_dfs_2011_agecombined[i].rename(columns={'local authority: district / unitary (prior to April 2015)': 'laua_name'}, 
                                        inplace=True)
test_dfs_2011_agecombined['Aged 25 to 34 years']

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,Adur,E07000223,1065,3589,184,521,278,2,80,494,159,122,6494,5637,857,5359
1,Allerdale,E07000026,1794,5380,175,582,551,10,91,512,327,152,9574,8482,1092,7931
2,Amber Valley,E07000032,1953,7560,273,813,740,6,160,848,393,242,12988,11339,1649,10599
3,Arun,E07000224,2324,8206,337,1038,653,14,170,1003,383,376,14504,12558,1946,11905
4,Ashfield,E07000170,2240,7908,281,691,967,7,156,1141,503,320,14214,12087,2127,11120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,Wychavon,E07000238,1645,6456,274,724,529,9,154,583,232,217,10823,9628,1195,9099
344,Wycombe,E07000007,2692,13182,647,1481,923,18,390,1603,298,508,21742,18925,2817,18002
345,Wyre,E07000128,1728,5184,261,775,542,11,167,519,321,155,9663,8490,1173,7948
346,Wyre Forest,E07000239,1640,5838,228,645,629,8,122,669,350,213,10342,8980,1362,8351


Using wikipedia I have managed to ascertain which locations unique to the 2011 dataset make up the unique locations of the 2021 dataset.  I have stored them in a dictionary below. NOTE** St Edmundsbury likely refers instead to bury st.edmunds, the former being the name of the cathedral located in the latter.  I will leave this as is just now but may have to change this later

In [84]:
district_change_dict = {
    'Bournemouth, Christchurch and Poole': ['Bournemouth', 'Christchurch', 'Poole'],
    'Buckinghamshire': ['South Bucks',  'Chiltern', 'Wycombe', 'Aylesbury Vale'],
    'Dorset': ['Weymouth and Portland', 'West Dorset', 'North Dorset', 'Purbeck', 'East Dorset'],
    'East Suffolk': ['Suffolk Coastal', 'Waveney'],
    'North Northamptonshire': ['Corby', 'East Northamptonshire', 'Kettering', 'Wellingborough'],
    'Somerset West and Taunton': ['Taunton Deane', 'West Somerset'],
    'West Northamptonshire': ['Daventry', 'Northampton', 'South Northamptonshire'],
    'West Suffolk': ['Forest Heath', 'St Edmundsbury']
    
    
}

I will also require the laua codes for the new districts which I will get below

In [85]:
temp = test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 16 to 24 years'].loc[test_dfs['df_nomis_2023_08_06_172146.xlsx']
                    ['Aged 16 to 24 years']['2022 local authorities: district'].isin(['Bournemouth, Christchurch and Poole',
 'Buckinghamshire',
 'Dorset',
 'East Suffolk',
 'North Northamptonshire',
 'Somerset West and Taunton',
 'West Northamptonshire',
 'West Suffolk'])]
temp= temp.sort_values(by='2022 local authorities: district' )
temp


,2022 local authorities: district,laua_code,Economically active (excluding full-time students): In employment,Economically active (excluding full-time students): Unemployed,Economically active and a full-time student: In employment,Economically active and a full-time student: Unemployed,Economically inactive (excluding full-time students),Economically inactive and a full-time student,Age Group,Total Residents,Total Active,Total Inactive,Total Employed
289,"Bournemouth, Christchurch and Poole",E06000058,14769,1901,5193,2429,2729,18308,Aged 16 to 24 years,45329,24292,21037,19962
227,Buckinghamshire,E06000060,20336,2390,4546,1527,3324,17497,Aged 16 to 24 years,49620,28799,20821,24882
290,Dorset,E06000059,13766,1391,2982,956,2504,8686,Aged 16 to 24 years,30285,19095,11190,16748
180,East Suffolk,E07000244,9256,1145,1737,720,1823,5649,Aged 16 to 24 years,20330,12858,7472,10993
76,North Northamptonshire,E06000061,15577,1683,2987,1202,2754,8907,Aged 16 to 24 years,33110,21449,11661,18564
308,Somerset West and Taunton,E07000246,6297,627,1191,409,1008,3701,Aged 16 to 24 years,13233,8524,4709,7488
77,West Northamptonshire,E06000062,18217,2006,4767,1922,2956,13119,Aged 16 to 24 years,42987,26912,16075,22984
181,West Suffolk,E07000245,9455,749,1420,413,1541,3900,Aged 16 to 24 years,17478,12037,5441,10875


In [86]:
district_codes = temp['laua_code'].tolist()
district_codes


['E06000058',
 'E06000060',
 'E06000059',
 'E07000244',
 'E06000061',
 'E07000246',
 'E06000062',
 'E07000245']

In [87]:
district_change_dict

{'Bournemouth, Christchurch and Poole': ['Bournemouth',
  'Christchurch',
  'Poole'],
 'Buckinghamshire': ['South Bucks', 'Chiltern', 'Wycombe', 'Aylesbury Vale'],
 'Dorset': ['Weymouth and Portland',
  'West Dorset',
  'North Dorset',
  'Purbeck',
  'East Dorset'],
 'East Suffolk': ['Suffolk Coastal', 'Waveney'],
 'North Northamptonshire': ['Corby',
  'East Northamptonshire',
  'Kettering',
  'Wellingborough'],
 'Somerset West and Taunton': ['Taunton Deane', 'West Somerset'],
 'West Northamptonshire': ['Daventry',
  'Northampton',
  'South Northamptonshire'],
 'West Suffolk': ['Forest Heath', 'St Edmundsbury']}

Im happy I've got the codes and the district changes I will now try to complete the changes.  Firstly I will get a note of two of the groups of districts' information to ensure the changes are correctly implemented

In [88]:
west_suff_df = test_dfs_2011_agecombined['Aged 25 to 34 years'].loc[test_dfs_2011_agecombined['Aged 25 to 34 years']
                                                                   ['laua_name'].isin(['Forest Heath', 'St Edmundsbury'])]
borne_df = test_dfs_2011_agecombined['Aged 25 to 34 years'].loc[test_dfs_2011_agecombined['Aged 25 to 34 years']
                                                                   ['laua_name'].isin(['Bournemouth',
  'Christchurch',
  'Poole'])]
west_suff_df

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
111,Forest Heath,E07000201,1134,6522,170,488,355,1,122,763,154,373,10082,8669,1413,8314
272,St Edmundsbury,E07000204,2021,8454,294,769,524,5,150,742,259,541,13759,12062,1697,11538


In [89]:
borne_df

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
26,Bournemouth,E06000028,4170,17066,678,1963,1362,19,1093,1525,745,623,29244,25239,4005,23877
65,Christchurch,E07000048,642,2174,100,298,201,6,59,259,104,55,3898,3415,483,3214
216,Poole,E06000029,2584,10458,423,1105,721,8,290,1199,433,326,17547,15291,2256,14570


In [90]:
#bournemouth, christchurch and poole residents number 25-34
29244+3898+17547

50689

In [91]:
#west suffolk total residents 25-34
10082+ 13759

23841

**The four cells above show that this is a correct implementation of the changes required, I will now complete the changes for all 8 districts.**

In [92]:
cols = test_dfs_2011_agecombined[i].columns
for i in test_dfs_2011_agecombined:
    index= 0
    cols = test_dfs_2011_agecombined[i].columns
    for j in district_change_dict:
        tmp_df = test_dfs_2011_agecombined[i].loc[test_dfs_2011_agecombined[i]['laua_name'].isin(district_change_dict[j])].copy()
        tmp_df['laua_code'] = district_codes[index]
        tmp_df['laua_name'] = j
        tmp_df = tmp_df.groupby(['laua_name', 'laua_code'])[cols[2:]].sum().reset_index()
        print(j)
        print(district_codes[index])
        test_dfs_2011_agecombined[i] = pd.concat([test_dfs_2011_agecombined[i], tmp_df])
        index+=1
      
    

Bournemouth, Christchurch and Poole
E06000058
Buckinghamshire
E06000060
Dorset
E06000059
East Suffolk
E07000244
North Northamptonshire
E06000061
Somerset West and Taunton
E07000246
West Northamptonshire
E06000062
West Suffolk
E07000245
Bournemouth, Christchurch and Poole
E06000058
Buckinghamshire
E06000060
Dorset
E06000059
East Suffolk
E07000244
North Northamptonshire
E06000061
Somerset West and Taunton
E07000246
West Northamptonshire
E06000062
West Suffolk
E07000245
Bournemouth, Christchurch and Poole
E06000058
Buckinghamshire
E06000060
Dorset
E06000059
East Suffolk
E07000244
North Northamptonshire
E06000061
Somerset West and Taunton
E07000246
West Northamptonshire
E06000062
West Suffolk
E07000245
Bournemouth, Christchurch and Poole
E06000058
Buckinghamshire
E06000060
Dorset
E06000059
East Suffolk
E07000244
North Northamptonshire
E06000061
Somerset West and Taunton
E07000246
West Northamptonshire
E06000062
West Suffolk
E07000245
Bournemouth, Christchurch and Poole
E06000058
Buckingham

In [93]:
for i in test_dfs_2011_agecombined:
    print(len(test_dfs_2011_agecombined[i]))

356
356
356
356
356


In [94]:
print(test_dfs_2011_agecombined.keys())

dict_keys(['Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years', 'Aged 50 to 64 years', 'Aged 65 years and over'])


The above shows there is now 356 rows in the 2011 dataframes, 8 more than before meaning all 8 combined districts have now been added.  I will now drop the rows pertaining to the old districts which should leave 331 rows as with the 2021 data.  I will also check Bournemouth and west suffolk to see if the figures have been added correctly.

In [95]:
drop_list = ['Aylesbury Vale',
 'Bournemouth',
 'Chiltern',
 'Christchurch',
 'Corby',
 'Daventry',
 'East Dorset',
 'East Northamptonshire',
 'Forest Heath',
 'Kettering',
 'North Dorset',
 'Northampton',
 'Poole',
 'Purbeck',
 'South Bucks',
 'South Northamptonshire',
 'St Edmundsbury',
 'Suffolk Coastal',
 'Taunton Deane',
 'Waveney',
 'Wellingborough',
 'West Dorset',
 'West Somerset',
 'Weymouth and Portland',
 'Wycombe']

In [96]:
for i in test_dfs_2011_agecombined:
    test_dfs_2011_agecombined[i].drop(test_dfs_2011_agecombined[i].loc[test_dfs_2011_agecombined[i]
                                ['laua_name'].isin(drop_list)].index, inplace=True)
    print(len(test_dfs_2011_agecombined[i]))

331
331
331
331
331


In [97]:
check_df = test_dfs_2011_agecombined['Aged 25 to 34 years'].loc[test_dfs_2011_agecombined['Aged 25 to 34 years']
                                                                   ['laua_name'].isin(['Bournemouth, Christchurch and Poole',
                                                                                 'West Suffolk'])]
check_df

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed
0,"Bournemouth, Christchurch and Poole",E06000058,7396,29698,1201,3366,2284,33,1442,2983,1282,1004,50689,43945,6744,41661
0,West Suffolk,E07000245,3155,14976,464,1257,879,6,272,1505,413,914,23841,20731,3110,19852


The above shows the total residents figures are 50689 and 23841 respectively which was the expected result.  I am happy that the figures are correct and that the data for each data set is comparable directly by area.  I will now finish off by adding the year and age band to the 2011 dataframes, combining them before changing the 'laua' to uppercase and performing final checks on the data. 

In [98]:
#add the age group and year
for i in test_dfs_2011_agecombined:
    test_dfs_2011_agecombined[i]['Age Group'] = i
    test_dfs_2011_agecombined[i]['Year'] = 2011
    

In [99]:
test_dfs_2011_agecombined.keys()

dict_keys(['Aged 16 to 24 years', 'Aged 25 to 34 years', 'Aged 35 to 49 years', 'Aged 50 to 64 years', 'Aged 65 years and over'])

In [100]:
test_dfs_2011_agecombined['Aged 25 to 34 years']

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed,Age Group,Year
0,Adur,E07000223,1065,3589,184,521,278,2,80,494,159,122,6494,5637,857,5359,Aged 25 to 34 years,2011
1,Allerdale,E07000026,1794,5380,175,582,551,10,91,512,327,152,9574,8482,1092,7931,Aged 25 to 34 years,2011
2,Amber Valley,E07000032,1953,7560,273,813,740,6,160,848,393,242,12988,11339,1649,10599,Aged 25 to 34 years,2011
3,Arun,E07000224,2324,8206,337,1038,653,14,170,1003,383,376,14504,12558,1946,11905,Aged 25 to 34 years,2011
4,Ashfield,E07000170,2240,7908,281,691,967,7,156,1141,503,320,14214,12087,2127,11120,Aged 25 to 34 years,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,East Suffolk,E07000244,3823,11555,539,1343,1190,16,204,1723,619,635,21647,18450,3197,17260,Aged 25 to 34 years,2011
0,North Northamptonshire,E06000061,5844,23148,763,2104,2156,17,385,2888,963,822,39090,34015,5075,31859,Aged 25 to 34 years,2011
0,Somerset West and Taunton,E07000246,2414,8555,344,1038,570,6,196,880,496,246,14745,12921,1824,12351,Aged 25 to 34 years,2011
0,West Northamptonshire,E06000062,6916,29027,1019,3080,2520,16,904,2887,943,1248,48560,42562,5998,40042,Aged 25 to 34 years,2011


In [101]:
combined_2011_df = test_dfs_2011_agecombined['Aged 16 to 24 years']
for i in test_dfs_2011_agecombined:
    if i != 'Aged 16 to 24 years':
        combined_2011_df = pd.concat([test_dfs_2011_agecombined[i], combined_2011_df])
combined_2011_df

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed,Age Group,Year
0,Darlington,E06000005,550,343,200,213,36,16612,19,44,192,230,18439,1342,17097,1306,Aged 65 years and over,2011
1,County Durham,E06000047,2239,1731,828,1081,105,82939,129,212,1517,1564,92345,5984,86361,5879,Aged 65 years and over,2011
2,Hartlepool,E06000001,336,291,90,102,25,14071,33,22,290,338,15598,844,14754,819,Aged 65 years and over,2011
3,Middlesbrough,E06000002,550,377,137,125,47,18446,42,56,456,455,20691,1236,19455,1189,Aged 65 years and over,2011
4,Northumberland,E06000057,1929,1250,1004,1181,95,56092,76,195,646,836,63304,5459,57845,5364,Aged 65 years and over,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,East Suffolk,E07000244,5307,7151,222,455,2735,13,4879,679,275,669,22385,15870,6515,13135,Aged 16 to 24 years,2011
0,North Northamptonshire,E06000061,6734,11394,213,627,3900,18,7091,1094,411,815,32297,22868,9429,18968,Aged 16 to 24 years,2011
0,Somerset West and Taunton,E07000246,3513,5296,134,343,1335,10,3454,409,190,361,15045,10621,4424,9286,Aged 16 to 24 years,2011
0,West Northamptonshire,E06000062,8859,13928,322,836,4538,20,10181,1047,429,1102,41262,28483,12779,23945,Aged 16 to 24 years,2011


In [102]:
#The +331 is to account for the lowest age band in the 2021 data which is not present in the 2011 data
#This 15 and under age band contains no values > 0 so it may be unnecceassary to keep it in but I'm keeping it for now
len(combined_2021_df) == (len(combined_2011_df) + 331)

True

In [103]:
combined_2011_df['laua_name'] = combined_2011_df['laua_name'].str.upper()

In [104]:
combined_2011_df

,laua_name,laua_code,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed,Age Group,Year
0,DARLINGTON,E06000005,550,343,200,213,36,16612,19,44,192,230,18439,1342,17097,1306,Aged 65 years and over,2011
1,COUNTY DURHAM,E06000047,2239,1731,828,1081,105,82939,129,212,1517,1564,92345,5984,86361,5879,Aged 65 years and over,2011
2,HARTLEPOOL,E06000001,336,291,90,102,25,14071,33,22,290,338,15598,844,14754,819,Aged 65 years and over,2011
3,MIDDLESBROUGH,E06000002,550,377,137,125,47,18446,42,56,456,455,20691,1236,19455,1189,Aged 65 years and over,2011
4,NORTHUMBERLAND,E06000057,1929,1250,1004,1181,95,56092,76,195,646,836,63304,5459,57845,5364,Aged 65 years and over,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,EAST SUFFOLK,E07000244,5307,7151,222,455,2735,13,4879,679,275,669,22385,15870,6515,13135,Aged 16 to 24 years,2011
0,NORTH NORTHAMPTONSHIRE,E06000061,6734,11394,213,627,3900,18,7091,1094,411,815,32297,22868,9429,18968,Aged 16 to 24 years,2011
0,SOMERSET WEST AND TAUNTON,E07000246,3513,5296,134,343,1335,10,3454,409,190,361,15045,10621,4424,9286,Aged 16 to 24 years,2011
0,WEST NORTHAMPTONSHIRE,E06000062,8859,13928,322,836,4538,20,10181,1047,429,1102,41262,28483,12779,23945,Aged 16 to 24 years,2011


In [105]:
###THIS CELL WAS ADDED TO MAKE THE COLUMN NAMES MATCH UP BETWEEN THE TWO YEARS DATA AND THE FIXED COLLECTION DATA
###THIS RECTIFIED AN EARLIER MISTAKE IN RENAMING THE COLUMNS
combined_2011_df.rename(columns={'laua_code': 'laua'}, 
                                        inplace=True)
combined_2021_df.rename(columns={'2022 local authorities: district': 'laua_name', 'laua_code': 'laua'}, 
                                        inplace=True)
print(combined_2011_df[:2])
print(combined_2021_df[:2])

       laua_name       laua  \
0     DARLINGTON  E06000005   
1  COUNTY DURHAM  E06000047   

   Economically active: In employment: Employee: Part-time (including full-time students)  \
0                                                550                                        
1                                               2239                                        

   Economically active: In employment: Employee: Full-time (including full-time students)  \
0                                                343                                        
1                                               1731                                        

   Economically active: In employment: Self-employed: Part-time (including full-time students)  \
0                                                200                                             
1                                                828                                             

   Economically active: In employment: Self-employe

In [106]:
combined_2011_df

,laua_name,laua,Economically active: In employment: Employee: Part-time (including full-time students),Economically active: In employment: Employee: Full-time (including full-time students),Economically active: In employment: Self-employed: Part-time (including full-time students),Economically active: In employment: Self-employed: Full-time (including full-time students),Economically active: Unemployed (including full-time students),Economically inactive: Retired,Economically inactive: Student (including full-time students),Economically inactive: Looking after home or family,Economically inactive: Long-term sick or disabled,Economically inactive: Other,Total Residents,Total Active,Total Inactive,Total Employed,Age Group,Year
0,DARLINGTON,E06000005,550,343,200,213,36,16612,19,44,192,230,18439,1342,17097,1306,Aged 65 years and over,2011
1,COUNTY DURHAM,E06000047,2239,1731,828,1081,105,82939,129,212,1517,1564,92345,5984,86361,5879,Aged 65 years and over,2011
2,HARTLEPOOL,E06000001,336,291,90,102,25,14071,33,22,290,338,15598,844,14754,819,Aged 65 years and over,2011
3,MIDDLESBROUGH,E06000002,550,377,137,125,47,18446,42,56,456,455,20691,1236,19455,1189,Aged 65 years and over,2011
4,NORTHUMBERLAND,E06000057,1929,1250,1004,1181,95,56092,76,195,646,836,63304,5459,57845,5364,Aged 65 years and over,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,EAST SUFFOLK,E07000244,5307,7151,222,455,2735,13,4879,679,275,669,22385,15870,6515,13135,Aged 16 to 24 years,2011
0,NORTH NORTHAMPTONSHIRE,E06000061,6734,11394,213,627,3900,18,7091,1094,411,815,32297,22868,9429,18968,Aged 16 to 24 years,2011
0,SOMERSET WEST AND TAUNTON,E07000246,3513,5296,134,343,1335,10,3454,409,190,361,15045,10621,4424,9286,Aged 16 to 24 years,2011
0,WEST NORTHAMPTONSHIRE,E06000062,8859,13928,322,836,4538,20,10181,1047,429,1102,41262,28483,12779,23945,Aged 16 to 24 years,2011


In [107]:
#check for null values
combined_2011_df.isna().sum()

laua_name                                                                                      0
laua                                                                                           0
Economically active: In employment: Employee: Part-time (including full-time students)         0
Economically active: In employment: Employee: Full-time (including full-time students)         0
Economically active: In employment: Self-employed: Part-time (including full-time students)    0
Economically active: In employment: Self-employed: Full-time (including full-time students)    0
Economically active: Unemployed (including full-time students)                                 0
Economically inactive: Retired                                                                 0
Economically inactive: Student (including full-time students)                                  0
Economically inactive: Looking after home or family                                            0
Economically inactive: Long-te

**I'm happy with the results above I believe the data has been suitably cleaned and is now ready to import into MongoDb.**

**EDIT** 

Having moved on from this notebook I realised that it might be worth while to estimate the part time to full time ratio of the 2021 data as this only categorises people 'In Employment' and doesn't draw the distinction.  I'm going to do this between here and the next bold markdown cell to show this was done later**

In [108]:
#cols

In [109]:
#combined_2011_df['F/T to P/T ratio'] = (combined_2011_df[cols[3]] + combined_2011_df[cols[5]])/(combined_2011_df[cols[2]]+ combined_2011_df[cols[4]])

In [110]:
#combined_2011_df

**the code lines above worked as expected however I have commented them out as they were messing with the code already written in the next notebook.  I kept them in here though in case I needed this later. End of update**

In [111]:
# Drop the fixed_broadband_collection collection
mongo_db.drop_collection('census_employment_collection')

{'ok': 0.0,
 'errmsg': 'ns not found',
 'code': 26,
 'codeName': 'NamespaceNotFound'}

In [112]:
census_collection = mongo_db["census_employment_collection"]

In [113]:
census_collection.insert_many(combined_2011_df.to_dict(orient='records'))

In [114]:
census_collection.insert_many(combined_2021_df.to_dict(orient='records'))

In [115]:
census_collection.count_documents({})

3641

##old experiment, kept to remember code but otherwise irrelevent.  All cells have been changed to markdown below here

for a, df in test_dfs_2011_agecombined.items():
    print(a)
    census_collection.insert_many(df.to_dict(orient='records'))

census_collection.count_documents({})

1655/5


for a, df in test_dfs['df_nomis_2023_08_06_172146.xlsx'].items():
    print(a)
    census_collection.insert_many(df.to_dict(orient='records'))

census_collection.count_documents({})

3641/11

##### 



test_df1= test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 16 to 19']
new_cols = test_df1.loc[0].tolist()
old_cols = test_df1.columns
new_cols[1] = 'laua_code'

for i in range(len(old_cols)):
    test_df1.rename(columns= {old_cols[i]: new_cols[i]}, inplace =True)
    
    

test_df1

new_2011_dfs = {}
##old experiment, kept to remember code but otherwise irrelevent
for j in test_dfs['df_nomis_2023_08_06_174635.xlsx'].keys():
    df = test_dfs['df_nomis_2023_08_06_174635.xlsx'][j]
    for k in range(len(old_cols)):
        df.rename(columns= {old_cols[k]: new_cols[k]}, inplace =True)
    print('balls')   
    df[new_cols[2:]] = df[new_cols[2:]].astype(int)
    totals = []
    active_totals = []
    inactive_totals = []
    employed = []
    for index, row in df.iterrows():
        totals.append(row[new_cols[2:]].sum())
        employed.append(row[new_cols[2:6]].sum())
        active_totals.append(row[new_cols[2:7]].sum())
        inactive_totals.append(row[new_cols[7:]].sum())
    df['Active'] = active_totals
    df['Inactive'] = inactive_totals
    df['Total Employed'] = employed
    df['Population'] = totals
    new_2011_dfs[j] = df

new_2011_dfs['Age 16 to 19'].head()


The cell above shows there is an issue with the third age group as the print statement only executes twice. I'll investigate further

test_df2 = test_dfs['df_nomis_2023_08_06_174635.xlsx']['Age 22 to 24']
test_df2#[new_cols[2:]] = test_df2[new_cols[2:]].astype(int)

Right i can see theres a metadata row still included here which is clearly causing the problem.  I need to investigate why this is happening and why it hasn't happened with the first two

for i in test_dfs['df_nomis_2023_08_06_174635.xlsx'].keys():
    print(test_dfs['df_nomis_2023_08_06_174635.xlsx'][i]['Unnamed: 0','Unnamed: 1'][:3])
    print()

test_df1.drop([0], inplace=True)
test_df1

test_df1.describe()


test_df1.dtypes

##get the data types right for adding values
test_df1[new_cols[2:]] = test_df1[new_cols[2:]].astype(int)
test_df1.dtypes

#okay no nulls great
test_df1.isna().sum()

new_cols[2:]

#calculate totals and add columns with these values
totals = []
active_totals = []
inactive_totals = []
employed = []
for index, row in test_df1.iterrows():
    totals.append(row[new_cols[2:]].sum())
    employed.append(row[new_cols[2:6]].sum())
    active_totals.append(row[new_cols[2:7]].sum())
    inactive_totals.append(row[new_cols[7:]].sum())
test_df1['Active'] = active_totals
test_df1['Inactive'] = inactive_totals
test_df1['Total Employed'] = employed
test_df1['Population'] = totals
test_df1

    

test_df1.dtypes

####check if there are any values > 0 in the 15 and under data
test_dfs['df_nomis_2023_08_06_172146.xlsx']['Aged 15 years and under'].sum()